<?php

/**
 * Main index for the NetworkCurator system. 
 * All user interaction should got through here.
 * 
 */

// load the settings for the website
include_once "nc-admin/config/nc-config.php";


// load helper functions
$PP = $_SERVER['DOCUMENT_ROOT'] . NC_PHP_PATH;
$UP = $_SERVER['DOCUMENT_ROOT'] . NC_UI_PATH;
include_once "nc-api/helpers/GeneralApiCaller.php";
include_once $PP . "/NCApiCaller.php";
include_once $PP . "/nc-sessions.php";
include_once $PP . "/nc-generic.php";
include_once $UP . "/nc-components.php";


// get two common fields from the url
$page = $_REQUEST['page'];
$network = $_REQUEST['network'];


// collect information about the user from the session
session_start();
$uid = $_SESSION['uid'];
$upw = $_SESSION['upw'];
$NCapi = new NCApiCaller($uid, $upw);
$userin = $NCapi->checkLogin();
if (!$userin) {    
    print_r($userin);
    $uid = "guest";
}
$userip = $_SERVER['REMOTE_ADDR'];


if ($page === "logout") {
    ncSignout();
}

// create a basic structure for all pages with header, navbar
include_once "nc-ui/nc-components/nc-header.php";
include_once "nc-ui/nc-components/nc-navbar.php";

// the middle portion of the page is generated by scripts in nc-ui
if ($page == "login" || $page == "logout" || $page == "admin") {
    // these are pages that require only a user id
    include_once "nc-ui/nc-ui-$page.php";
} else if ($page=="network") {
    // these are pages that require a set network name
    if (!$network) {
        include_once "nc-ui/nc-ui-front.php";
    } else {
        include_once "nc-ui/nc-ui-$page.php";
    }    
} else {
    include_once "nc-ui/nc-ui-front.php";
}

// the footer is common to all pages
include_once "nc-ui/nc-components/nc-footer.php";


exit();
?>
