#!/bin/bash


## script to pull an update and build local js and css

echo ""
echo "Updating NetworkCurator core"
git pull

echo ""
echo "Updating NetworkCurator user interface"
cd nc-ui
git pull
cd ..

echo ""
echo "Updating NetworkCurator configuration"
cd nc-admin/install
php configure.php
cd ../..

echo ""
echo "Building javascript and css files"

## build javascript
cd nc-core
rm -fr js
mkdir js
cat js-src/nc-core.js \
    js-src/nc-utils.js \
    js-src/nc-admin.js \
    js-src/nc-data.js \
    js-src/nc-graph.js \
    js-src/nc-graphsim.js \
    js-src/nc-object.js \
    js-src/nc-ontology.js \
    js-src/nc-sandbox.js \
    js-src/nc-ui.js \
    js-src/nc-users.js \
    js-src/nc-history.js \
      > js/networkcurator.js
php ../nc-admin/tools/simple-minify.php js/networkcurator.js js/networkcurator.min.js
cat includes/*/*min.js includes/*/*/*min.js > js/networkcurator-includes.min.js


## build css
rm -fr css
mkdir css
cat css-src/nc-core.css > css/nc-core.css
php ../nc-admin/tools/simple-minify.php css/nc-core.css css/nc-core.min.css

echo "Done"
